query($articleId: ID!) {
  getArticle(articleId: $articleId){
    title
    createdDate
    editDate
    faculty
    isSubmitted
    toBePublished
    submittedBy {
      firstName
      lastName
    }
    article{
      path
    }
    picture{
      path
    }
  }
}
