query($articleId: ID!) {
  getArticle(articleId: $articleId){
    title
    createdDate
    editDate
    faculty
    isSubmitted
    toBePublished
    submittedBy {
      _id
      firstName
      lastName
    }
    academicYear {
      submissionClose
    }
    article{
      path
    }
    picture{
      path
    }
    messages{
      messageUser{
        username
      }
      messageDate
      messageBody
    }
  }
}
