query{
  getPublicationSelections{
    _id
    title
    faculty
    submittedBy{
      firstName
      lastName
    }
    article {
      filename
      path
      mimetype
    }
    picture {
      filename
      path
      filename
    }
  }
}
