query($submissionId: ID!) {
  getSubmission(submissionId: $submissionId){
    title
    createdDate
    faculty
    submittedBy {
      firstName
      lastName
    }
    article{
      path
    }
    picture{
      path
    }
  }
}
