query($submissionId: ID!) {
  getSubmission(
    submissionId: $submissionId
  ) {
    title
    createdDate
    submittedBy {
      firstName
      lastName
      faculty
    }
    article {
      path
    }
  }
}
